---
title: Feestknaller
hero_image: images/banner.png
description:
  - Make a reusable party popper that rewards you with a light and sound
  - display when it is pulled
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: You will make
  - 
    title: Laat je RGB LED branden
  - 
    title: Maak een geluid
    completion:
      - engaged
  - 
    title: Activeer je feestknaller
  - 
    title: Maak je schakelaar
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Verbeter je project
  - 
    title: Wat kun je verder nog doen?
