---
title: مفرقعات الحفلة
hero_image: images/banner.png
description: اصنع مفرقعات للحفلة قابل لإعادة الاستخدام يكافئك بعرض ضوئي وصوتي عند سحبه
version: 4
listed: true
copyedit: true
last_tested: '2021-03-26'
steps:
  - 
    title: المقدمة
  - 
    title: قم بإضاءة RGB LED الخاص بك
  - 
    title: أصدِر ضوضاءً
    completion:
      - engaged
  - 
    title: قم بتنشيط مفرقعات الحفلة
  - 
    title: قم بصنع مفتاح التشغيل الخاص بك
    completion:
      - internal
  - 
    title: تفكير
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: قم بترقية او تطوير مشروعك
  - 
    title: ما هي الخطوة التالية؟
