---
title: Bombe de fête
hero_image: images/banner.png
description: Fabriquer une bombe de fête réutilisable qui te récompense avec un affichage lumineux et sonore lorsqu'elle est tirée
version: 4
listed: true
copyedit: true
last_tested: '2021-03-26'
steps:
  - 
    title: Introduction
  - 
    title: Allumer ta LED RVB
  - 
    title: Faire du bruit
    completion:
      - engaged
  - 
    title: Activer ta bombe de fête
  - 
    title: Fabriquer ton interrupteur
    completion:
      - internal
  - 
    title: Réflexion
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Améliorer ton projet
  - 
    title: Et ensuite ?
